### ISSUE TITLE
Claim ownership of app on splunkbase

### ISSUE THREAD

**Issue by sbs2001** [splunk-soar-connectors/crowdsec#5]
The app has been published at https://splunkbase.splunk.com/app/6791. We'd like to have our name on `Created By` and provide support too. 

cc @rgil-splunk

**Comment by nastorSplunk** [comment]
@sbs2001 Please reach out to me at nastor@splunk.com to discuss creating a Developer Supported Connector

**Comment by sbs2001** [comment]
done. Thanks @nastorSplunk
